import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const lessons = [
  // Unit 1: Home Row
  {
    title: 'f and j Keys',
    description: 'Start with the index finger anchor keys on the home row.',
    content: 'fjfjfj jfjfjf fj jf jjff ffjj fjfj jfjf ff jj fj jf fjjf jffj fjfjfjfj jfjfjfjf ffjj jjff fj jf',
    type: 'SCRIPTED' as const,
    level: 1,
    order: 1,
    unit: 'Home Row',
    targetKeys: ['f', 'j'],
    minWpm: 15,
    minAccuracy: 0.9,
  },
  {
    title: 'd and k Keys',
    description: 'Add the middle finger keys to your home row practice.',
    content: 'dk kd dkdk kdkd dd kk fdk jkd fdj jkf dfjk kjfd fdjk dkfj kjdf fdkj dkdk kdkd fdk jkf dfjk kjfd',
    type: 'SCRIPTED' as const,
    level: 1,
    order: 2,
    unit: 'Home Row',
    targetKeys: ['d', 'k'],
    minWpm: 15,
    minAccuracy: 0.9,
  },
  {
    title: 's and l Keys',
    description: 'Practice the ring finger keys on the home row.',
    content: 'sl ls slsl lsls ss ll fsl jlk sdk jlk sld lks sldf lkdf sldk ldsk sdlk lsdk sfld jlks sldf lksd',
    type: 'SCRIPTED' as const,
    level: 1,
    order: 3,
    unit: 'Home Row',
    targetKeys: ['s', 'l'],
    minWpm: 15,
    minAccuracy: 0.9,
  },
  {
    title: 'a and Semicolon Keys',
    description: 'Complete the home row with the pinky finger keys.',
    content: 'a; ;a a;a ;a; aa ;; fa; ja; sa; la; asd ;lk a;s ;lk asd; lkj; asdf jkl; a;sl ;lka',
    type: 'SCRIPTED' as const,
    level: 1,
    order: 4,
    unit: 'Home Row',
    targetKeys: ['a', ';'],
    minWpm: 15,
    minAccuracy: 0.9,
  },
  {
    title: 'Home Row Review',
    description: 'Practice all home row keys together.',
    content: 'asdfjkl; ;lkjfdsa asdf jkl; alsk fjdk safl jkda asdfjkl ;lkjfds asdf;lkj jkl;asdf fdsa;lkj',
    type: 'SCRIPTED' as const,
    level: 1,
    order: 5,
    unit: 'Home Row',
    targetKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
    minWpm: 18,
    minAccuracy: 0.9,
  },
  {
    title: 'Home Row Words',
    description: 'Type real words using only home row keys.',
    content: 'flask lass lads fads asks jabs dabs labs salsa dads falls adds lass fads asks jabs dabs flak flask sal lad fad dab lab ask fall lass dads',
    type: 'SCRIPTED' as const,
    level: 1,
    order: 6,
    unit: 'Home Row',
    targetKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
    minWpm: 20,
    minAccuracy: 0.9,
  },

  // Unit 2: Top Row
  {
    title: 'r and u Keys',
    description: 'Reach up from f and j to the top row index finger keys.',
    content: 'ru ur ruru uurr fru jur dru kur sru lur aru ruff ruse rut run fur fun rug rub rum rule ruler',
    type: 'SCRIPTED' as const,
    level: 2,
    order: 7,
    unit: 'Top Row',
    targetKeys: ['r', 'u'],
    minWpm: 20,
    minAccuracy: 0.9,
  },
  {
    title: 'e and i Keys',
    description: 'Practice the middle finger top row keys.',
    content: 'ei ie eiei iiee fei jik dei kie sei lie edit idle side ride idea fire hire tire wide life time',
    type: 'SCRIPTED' as const,
    level: 2,
    order: 8,
    unit: 'Top Row',
    targetKeys: ['e', 'i'],
    minWpm: 20,
    minAccuracy: 0.9,
  },
  {
    title: 't and y Keys',
    description: 'Add the center index finger top row keys.',
    content: 'ty yt tyty yytt fty jyt dty kyt sty lyt type yet try toy they stay year your tiny tray style tyrant',
    type: 'SCRIPTED' as const,
    level: 2,
    order: 9,
    unit: 'Top Row',
    targetKeys: ['t', 'y'],
    minWpm: 22,
    minAccuracy: 0.9,
  },
  {
    title: 'w and o Keys',
    description: 'Practice the ring finger top row keys.',
    content: 'wo ow wowo ooww fwo jow dwo kow sow low work owls word wow own flow grow slow show glow blow crow',
    type: 'SCRIPTED' as const,
    level: 2,
    order: 10,
    unit: 'Top Row',
    targetKeys: ['w', 'o'],
    minWpm: 22,
    minAccuracy: 0.9,
  },
  {
    title: 'q and p Keys',
    description: 'Complete the top row with the pinky finger keys.',
    content: 'qp pq qpqp ppqq fqp jpq dqp kqp sqp lqp quiz plow plan prep prop plus play plea plea park part',
    type: 'SCRIPTED' as const,
    level: 2,
    order: 11,
    unit: 'Top Row',
    targetKeys: ['q', 'p'],
    minWpm: 22,
    minAccuracy: 0.9,
  },
  {
    title: 'Top Row Review',
    description: 'Review all top row keys with common words.',
    content: 'quick power tower query prose write prior outer quite power type word your work grow play quiz quite power quite write tower query prose',
    type: 'SCRIPTED' as const,
    level: 2,
    order: 12,
    unit: 'Top Row',
    targetKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    minWpm: 25,
    minAccuracy: 0.9,
  },
  {
    title: 'Common Words I',
    description: 'Practice the most frequently used English words.',
    content: 'the and for are but not you all can her was one our out day get has him his how its may new now old see two way who did its let put say she too use',
    type: 'SCRIPTED' as const,
    level: 2,
    order: 13,
    unit: 'Top Row',
    targetKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    minWpm: 25,
    minAccuracy: 0.9,
  },

  // Unit 3: Bottom Row
  {
    title: 'v and m Keys',
    description: 'Reach down from f and j to the bottom row index finger keys.',
    content: 'vm mv vmvm mmvv fvm jmv dvm kmv svm lmv move valve very most must much more make came same name game',
    type: 'SCRIPTED' as const,
    level: 3,
    order: 14,
    unit: 'Bottom Row',
    targetKeys: ['v', 'm'],
    minWpm: 25,
    minAccuracy: 0.9,
  },
  {
    title: 'c and Comma Keys',
    description: 'Practice the middle finger bottom row key and comma.',
    content: 'nice, rice, face, lace, race, place, grace, space, trace, brace, price, twice, since, dance, fence, hence, once, bounce, pounce, ounce,',
    type: 'SCRIPTED' as const,
    level: 3,
    order: 15,
    unit: 'Bottom Row',
    targetKeys: ['c', ','],
    minWpm: 25,
    minAccuracy: 0.9,
  },
  {
    title: 'x and Period Keys',
    description: 'Practice the ring finger bottom row key and period.',
    content: 'next. text. flex. apex. axis. exit. extra. exact. exist. excel. index. annex. inbox. pixel. boxed. foxes. mixed. fixed. taxed. waxed.',
    type: 'SCRIPTED' as const,
    level: 3,
    order: 16,
    unit: 'Bottom Row',
    targetKeys: ['x', '.'],
    minWpm: 25,
    minAccuracy: 0.9,
  },
  {
    title: 'z and Slash Keys',
    description: 'Complete the bottom row with the pinky keys.',
    content: 'size/zero zone/zip zeal/zone zero/size zone/zap zinc/zest zap/zip buzz/fizz jazz/haze gaze/maze daze/faze raze/zeal zoom/zone',
    type: 'SCRIPTED' as const,
    level: 3,
    order: 17,
    unit: 'Bottom Row',
    targetKeys: ['z', '/'],
    minWpm: 25,
    minAccuracy: 0.9,
  },
  {
    title: 'Full Alphabet',
    description: 'Practice all 26 letters of the alphabet.',
    content: 'abcdefghijklmnopqrstuvwxyz the quick brown fox jumps over the lazy dog pack my box with five dozen liquor jugs how vexingly quick daft zebras jump',
    type: 'SCRIPTED' as const,
    level: 3,
    order: 18,
    unit: 'Bottom Row',
    targetKeys: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
    minWpm: 28,
    minAccuracy: 0.9,
  },
  {
    title: 'Short Sentences',
    description: 'Type complete sentences for the first time.',
    content: 'the dog ran fast. a red fox can jump. ask me for the keys. just do it. she sat by the lake. he made a big plan. we can fix the old car.',
    type: 'SCRIPTED' as const,
    level: 3,
    order: 19,
    unit: 'Bottom Row',
    targetKeys: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
    minWpm: 28,
    minAccuracy: 0.9,
  },

  // Unit 4: Common Words
  {
    title: 'Top 100 Words',
    description: 'Build fluency with the most common English words.',
    content: 'the of and a to in is it you that he was for on are with as his they be at one have this from or had by but what some we can out there when all your which their said if do will each about how up its more time has look two go see no way could people my than first been its who now find any new take only come its over think also back after use two how our work first well way even want because any these give day most us',
    type: 'SCRIPTED' as const,
    level: 4,
    order: 20,
    unit: 'Common Words',
    targetKeys: [],
    minWpm: 30,
    minAccuracy: 0.9,
  },
  {
    title: 'Sight Words',
    description: 'Practice essential sight words for reading and typing fluency.',
    content: 'about after again air also any around away back because been before below between big both boy call came come could did does done down each every find first from girl give goes good great hand have help here high home into just keep know large last left life light like little long look made make many more most move much must name need next night off only open other over part place play put right said same school show small some soon spell still such take than that their them then there these thing think this those time today together too turn under until upon very want water way were what when where which who will with word world would year you young your',
    type: 'SCRIPTED' as const,
    level: 4,
    order: 21,
    unit: 'Common Words',
    targetKeys: [],
    minWpm: 30,
    minAccuracy: 0.9,
  },
  {
    title: 'Action Verbs',
    description: 'Type common action verbs to build vocabulary and speed.',
    content: 'run jump skip walk talk read write eat drink sleep play work learn type think speak listen watch drive swim climb build create design develop explore imagine investigate remember understand communicate collaborate participate demonstrate',
    type: 'SCRIPTED' as const,
    level: 4,
    order: 22,
    unit: 'Common Words',
    targetKeys: [],
    minWpm: 30,
    minAccuracy: 0.9,
  },
  {
    title: 'Short Sentences II',
    description: 'Practice typing complete sentences with common words.',
    content: 'she reads every day. he likes to run fast. we will go to the store. it is a good day to work. they came home late last night. the big brown dog sat by the door. please turn off the light when you leave.',
    type: 'SCRIPTED' as const,
    level: 4,
    order: 23,
    unit: 'Common Words',
    targetKeys: [],
    minWpm: 32,
    minAccuracy: 0.9,
  },
  {
    title: 'Medium Passage',
    description: 'Practice with a longer connected passage.',
    content: 'The sun rises in the east and sets in the west. Every morning, birds begin to sing as the light grows. People start their day with coffee or tea, making plans for the hours ahead. Children walk to school with backpacks full of books. Workers sit at their desks and open their computers. The world wakes up slowly, then all at once.',
    type: 'SCRIPTED' as const,
    level: 4,
    order: 24,
    unit: 'Common Words',
    targetKeys: [],
    minWpm: 32,
    minAccuracy: 0.9,
  },
  {
    title: 'Longer Passage',
    description: 'Build endurance with a more substantial passage.',
    content: 'Learning to type well is one of the most valuable skills you can develop in the modern world. When you type without looking at your keyboard, your thoughts can flow directly onto the screen without interruption. Professional typists often reach speeds of sixty to one hundred words per minute. With regular practice, even a beginner can achieve forty words per minute within a few months. The key is to focus on accuracy first, then gradually increase your speed. Never sacrifice correctness for the sake of going faster, because bad habits are much harder to unlearn than they are to avoid in the first place.',
    type: 'SCRIPTED' as const,
    level: 4,
    order: 25,
    unit: 'Common Words',
    targetKeys: [],
    minWpm: 35,
    minAccuracy: 0.9,
  },

  // Unit 5: Speed Building
  {
    title: 'Speed Builder I',
    description: 'Push your typing speed with this natural English passage.',
    content: 'It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way.',
    type: 'SCRIPTED' as const,
    level: 5,
    order: 26,
    unit: 'Speed Building',
    targetKeys: [],
    minWpm: 38,
    minAccuracy: 0.9,
  },
  {
    title: 'Speed Builder II',
    description: 'Type this classic passage with increasing confidence.',
    content: 'In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters. And God said, let there be light, and there was light. God saw that the light was good, and he separated the light from the darkness. God called the light day, and the darkness he called night. And there was evening, and there was morning, the first day of creation on this good earth.',
    type: 'SCRIPTED' as const,
    level: 5,
    order: 27,
    unit: 'Speed Building',
    targetKeys: [],
    minWpm: 38,
    minAccuracy: 0.9,
  },
  {
    title: 'Speed Builder III',
    description: 'A longer passage to test your speed and stamina.',
    content: 'To be, or not to be, that is the question: Whether it is nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles and by opposing end them. To die, to sleep, no more; and by a sleep to say we end the heart-ache and the thousand natural shocks that flesh is heir to. This is a consummation devoutly to be wished. To die, to sleep; to sleep, perchance to dream. Ay, there is the rub, for in that sleep of death what dreams may come.',
    type: 'SCRIPTED' as const,
    level: 5,
    order: 28,
    unit: 'Speed Building',
    targetKeys: [],
    minWpm: 40,
    minAccuracy: 0.9,
  },
  {
    title: 'Speed Builder IV',
    description: 'Challenge yourself with this extended passage.',
    content: 'Four score and seven years ago our fathers brought forth on this continent a new nation, conceived in liberty and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation or any nation so conceived and so dedicated can long endure. We are met on a great battlefield of that war. We have come to dedicate a portion of that field as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this.',
    type: 'SCRIPTED' as const,
    level: 5,
    order: 29,
    unit: 'Speed Building',
    targetKeys: [],
    minWpm: 40,
    minAccuracy: 0.9,
  },
  {
    title: 'Speed Builder V',
    description: 'The ultimate speed challenge. Type fast and accurately.',
    content: 'We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness. That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed. That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness.',
    type: 'SCRIPTED' as const,
    level: 5,
    order: 30,
    unit: 'Speed Building',
    targetKeys: [],
    minWpm: 40,
    minAccuracy: 0.9,
  },
]

async function main() {
  await prisma.lesson.deleteMany()
  await prisma.lesson.createMany({
    data: lessons,
  })
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
